on: 
  workflow_dispatch:
    inputs:
      device:
        description: 'Select device'     
        required: true
        type: choice
        options:
        - MT3000
      sourcecode:
        description: 'https://github.com/destan19/OpenAppFilter.git'     
        required: true
      pkgname:
        description: 'OpenAppFilter-mt3000'  
        required: true
      email:
        description: 'Git accuont email address'  
        required: false
      password:
        description: 'Git account password'  
        required: false
        
jobs:
  setpackage:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: build ipk
      id: build
      env:
        SOURCECODEURL: ${{ github.event.inputs.sourcecode }}
        PKGNAME: ${{ github.event.inputs.pkgname }}
        BOARD: ${{ github.event.inputs.device }}
        EMAIL: ${{ github.event.inputs.email }}
        PASSWORD: ${{ github.event.inputs.password }}
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ./build.sh
        ./build.sh

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.pkgname }}_related_ipks
        path: |
          ./*ipk*
